site_name: OpenAI Cmdlet
theme:
  name: material
  features:
    - navigation.instant
    - search.suggest
    - content.code.copy
plugins:
  - search
repo_url: https://github.com/Neroro64/OpenAICmdlet
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences